### ISSUE TITLE
Generating Videos with Scene Dynamics

### ISSUE THREAD

**Issue by lkffight** [Yuliang-Zou/tf_videogan#1]
I would like to ask you a question: the paper's video data is what kind of format as input, debugging the code is the key to those places?

**Comment by Yuliang-Zou** [comment]
Not quite sure what you are asking...
I think they just have a huge disk to store the video data, the format doesn't matter.

**Comment by Yuliang-Zou** [comment]
@lkffight 
Not quite sure what you are asking...
I think they just have a huge disk to store the video data, the format doesn't matter.

**Comment by lkffight** [comment]
@Yuliang-Zou I am now debugging this code, because the paper to the data set is too big, I would like to know what their format is their own collection of video, verify the views of this article. I am based on your procedures to debug, you explain the code ideas?

**Comment by Yuliang-Zou** [comment]
@lkffight 
1. I only implement the test mode of generator of the model. No training code, and no discriminator. (But I think you can get their model weight of discriminator easily by modifying my code)

2. Seems that the authors do not make some parts of the model weight public (i.e. the hospital scene, and you cannot use this to predict the future)

3. You can download a subset of the video from the authors' website, I believe.

**Comment by lkffight** [comment]
@Yuliang-Zou Thank you very much. Is it difficult to implement training code and predict future code? Are the three models' code different?

**Comment by Yuliang-Zou** [comment]
@lkffight I think it should be easy to implement.

**Comment by lkffight** [comment]
@Yuliang-Zou Is your video dataset downloaded from the official website of the author? Do you have that part of the video based on your debugging? The author provides a single data set is too big, I now is based on the GPU version of tensorflow, reproduce your code need to pay attention to what the problem?
