### ISSUE TITLE
如何输入自己想要的一张图片生成一段短视频，而不是将数据集中的图片生成视频

### ISSUE THREAD

**Issue by hnsywangxin** [Yuliang-Zou/tf_videogan#2]
您好：
     这两天刚了解了一下GAN，无意中发现您写的这个项目，感觉挺好玩的，就复现了一下您的代码，说实话，目前还是有很多地方不太懂，现在有两个问题希望您能给我解答一下，感谢！
1：我好像在您的代码里面没看到图片的输入，请问生成的短视频是来源哪些图片，假如我现在想输入自己的一张图片，生成一段视频，该如何进行
2：我看到您的代码中的鉴别器函数是空的，看了DCGAN中的代码实现，发现有鉴别器函数，缺失这个函数会不会导致生成视频效果不理想
再次感谢！期待您的回信。

**Comment by Yuliang-Zou** [comment]
@hnsywangxin 你好
目前这个代码的实现只有生成器，它的输入是一个高维的高斯噪声向量。因为作者没有提供根据静态图片生成未来预测的模型参数的下载，所以并不能做视频的未来预测。另外，这里没有实现训练代码，所以鉴别器那部分我就也没实现（不过实现起来应该比较容易）。已经训练好的模型，不需要鉴别器来帮助生成视频了。

**Comment by hnsywangxin** [comment]
@Yuliang-Zou 好的，非常感谢，我大概懂你意思了，我再去好好看看代码跟文献，谢谢
