### ISSUE TITLE
Is there any pretrained models?

### ISSUE THREAD

**Issue by Amaris168** [Yuliang-Zou/tf_videogan#3]
hello! Is there any pretrained models in your code? The video dataset is too large and I can't train a model from the very beginning. Thank you

**Comment by Yuliang-Zou** [comment]
Check this: https://github.com/Yuliang-Zou/tf_videogan#models

I don't have the model weights of conditional generation (given 1st frame) since the authors did not release that.

**Comment by Amaris168** [comment]
Thanks for your reply! But I mean the tensorflow version of  pretrained models, not a torch version. Do you have one?

**Comment by Yuliang-Zou** [comment]
@Amaris168 No. I also don't have enough space to store the video data.

**Comment by Amaris168** [comment]
Thank you all the same.
