### ISSUE TITLE
The torch7 to tensorflow model transfer code saved my day!

### ISSUE THREAD

**Issue by 17Skye17** [Yuliang-Zou/tf_videogan#4]
Hello, Yuliang. : ) @Yuliang-Zou 
I have been searching for torch7 to tensorflow model converters these days, but there are many converters for other DL framework except for torch7. I know this could be done by hand and your code inspires me.
BTW, do you have an useful torch7 to tensorflow model converter? Thank you.

**Comment by Yuliang-Zou** [comment]
I don't have such a converter. I think that's because torch model not only stores the weights, but also the network architecture. And if they define custom layers, it will be quite difficult to convert it to other formats.

**Comment by 17Skye17** [comment]
Thank you for your reply. @Yuliang-Zou
